# Generated by Django 3.2.8 on 2021-10-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certiinfo',
            name='user_name',
        ),
        migrations.AddField(
            model_name='certiinfo',
            name='type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certiinfo',
            name='certi',
            field=models.ImageField(upload_to='\\img'),
        ),
        migrations.AlterField(
            model_name='certiinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
