# Generated by Django 3.2.8 on 2021-10-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_certiinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certiinfo',
            name='certi',
            field=models.FileField(upload_to=''),
        ),
    ]
